export const actionTypes = {
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  POST_DATA_SUCCESS: "POST_DATA_SUCCESS",
  PUT_DATA_SUCCESS: "PUT_DATA_SUCCESS",
  DELETE_DATA_SUCCESS: "DELETE_DATA_SUCCESS",

  HTTP_404_ERROR: "HTTP_404_ERROR",
  HTTP_500_ERROR: "HTTP_500_ERROR",
  HTTP_403_ERROR: "HTTP_403_ERROR",
  HTTP_401_ERROR: "HTTP_401_ERROR",

  HTTP_OTHER_ERROR: "HTTP_OTHER_ERROR",

  CLOSE_ERROR_MODAL: "CLOSE_ERROR_MODAL",
  CLOSE_SUCCESS_MODAL: "CLOSE_SUCCESS_MODAL",
  //GET_HISTORY_DATA_SUCCESS: "GET_HISTORY_DATA_SUCCESS",
};

// export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
// export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
// export const PUT_DATA_SUCCESS = "PUT_DATA_SUCCESS";
// export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";

// export const HTTP_404_ERROR = "HTTP_404_ERROR";
// export const HTTP_500_ERROR = "HTTP_500_ERROR";
// export const HTTP_OTHER_ERROR = "HTTP_OTHER_ERROR";

// export const CLOSE_ERROR_MODAL = "CLOSE_ERROR_MODAL";
// export const CLOSE_SUCCESS_MODAL = "CLOSE_SUCCESS_MODAL";
