export const userActionTypes = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  CLOSE_SUCCESS_MODAL: "CLOSE_SUCCESS_MODAL",
  // LOGOUT: "LOGOUT",
  // GETALL_SUCCESS: "GETALL_SUCCESS",

  // DELETE_SUCCESS: "DELETE_SUCCESS",
};
